version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./app_data:/app/app_data
    env_file:
      - .env
    networks:
      - geneva_network

networks:
  geneva_network:
    name: geneva_network